# Generated by Django 4.1.7 on 2023-04-15 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0003_alter_acts_apellido'),
    ]

    operations = [
        migrations.AddField(
            model_name='acts',
            name='foto',
            field=models.ImageField(default='imgs/defaults/actSinFoto.jpg', upload_to='imgs/act/'),
        ),
        migrations.AddField(
            model_name='directores',
            name='foto',
            field=models.ImageField(default='imgs/defaults/dirSinFoto.jpg', upload_to='imgs/dir/'),
        ),
        migrations.AddField(
            model_name='peliculas',
            name='valoracion',
            field=models.IntegerField(default=1),
        ),
    ]
