# Generated by Django 4.1.7 on 2023-04-15 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0004_acts_foto_directores_foto_peliculas_valoracion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='peliculas',
            old_name='director',
            new_name='directores',
        ),
        migrations.RemoveField(
            model_name='peliculas',
            name='imagen',
        ),
        migrations.AddField(
            model_name='peliculas',
            name='portada',
            field=models.ImageField(default='imgs/defaults/pelSinFoto.jpg', upload_to='imgs/pel/'),
        ),
        migrations.DeleteModel(
            name='Preguntas',
        ),
    ]
