# Generated by Django 4.1.7 on 2023-04-30 00:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0010_rename_notas_articulos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='cuerpo',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
