# Generated by Django 4.1.7 on 2023-04-26 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mensajes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajes',
            name='mostrar_como_leido',
            field=models.BooleanField(default=False),
        ),
    ]
